# Overview

## Links

- [Database design (Lucid chart)](https://www.lucidchart.com/invitations/accept/5273bef4-c7d5-441d-9155-24498632c760)

## Test data

- Test data is stored as javascript objects
- path to test data `./test_data/data.js`

## Sprint 2 clarification (Database)

Deadline

- Week 8

Aim

1. Store all required information
2. Support all required queries
3. Model data to support desired relations
4. Interactive query testing web page

Not supporting 

1. No Multimedia 
2. Can't determine which documents user can access
   - Oliver is responsible for user access and authentication. 



## Database conventions

Document ID 

- Also known as file name
- Lowercase
- Syntax<descriptive_name>_id 
- Where <descriptive_name> is manually selected by me to make it easy to debug
- User generated data will have autogenerated id like 42OqXx2K1bX7V4CfHkGt

Fields

- Lowercase
- Words seperated by dash like artifacts_link

Database and subcollections

- Also known as a folder
- Capitalize
- Plurals
- List of collections
  -  Artifacts 
  - People
  - Addendums
  - Events
  - Users 

Important fields

- All documents exect User_authentication_files must have
  - date_created : the date and time the document was created
  - created_by : the name user who created the data


